weights_name = 'unet2'
weights_path = 'train_output/weights/'
loss_curve_path = 'train_output/loss_curves/'
dataset_path = 'data/'
train_objects = ['pattern_31_rod_train.pt']
validation_objects = ['pattern_31_rod_val.pt']
test_objects = ['pattern_31_rod_test.pt']
batch_size = 16
kernel_size = 3
val_loss_SMA_window = 10
training_learning_rate = 0.001
validation_loss_count_threshold = 5
weight_decay = 1e-06
activation_func = 'relu'
norm_scale = 0.9
train_indefinitely = True
CNN_dimensions = [64, 128, 256, 512, 1024]
upconv_stride = 2
downsample_factor = 0.5
maxpool_size = 2
model_type = 'unet'
input_tactile_image_size = (160, 213)
depth_image_blur_kernel = 1
#device = device(type='cuda', index=2)
depth_normalization_parameters = (-1.5, 0.0)
num_images_to_display_live = 5
use_difference_image = True
exclude_objects = []
